name: "Blade icon to code"

on:
  workflow_dispatch:
    inputs:
      

jobs:
  create-pr:
    runs-on: ubuntu-latest
    # ensure the job can push and open a PR
    permissions:
      contents: write
      pull-requests: write

    steps:
      # 1. checkout full history so we can push a new branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. decide what text weâ€™ll put in the file
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install Yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: |
         cd packages/blade
         yarn install --frozen-lockfile
      
      - name: Update icons.json
        env:
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
        run: |
          cd packages/blade
          node ./scripts/getSvgFromFigma.js
  
  
      - name : Update icons Script
        run: |
         cd packages/blade
         node ./scripts/generateIcons.mjs
      # 4. create the pull request
      - name : Update React Tests 
        run: |
         cd packages/blade
         yarn run test:react Icons --updateSnapshot 

      - name : Update React Tests 
        run: |
          cd packages/blade
          yarn run test:react-native Icons --updateSnapshot 
         
      - name: Lint Source Code
        run: yarn lint:fix
        continue-on-error: true

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: add random file ${{ github.event.inputs.filename }}"
          branch: random-file-${{ github.run_id }}
          base: master
          title: "feat: add random file"
          body: |
            This PR was automatically generated by the **Create Random File PR** workflow.
            It adds `${{ github.event.inputs.filename }}` containing random or provided text.
          delete-branch: true
      # cleans up after merge
