name: Blade Tokens Upload

on: 
  workflow_dispatch:
    inputs:
      tokens:
        description: 'Token Object'
        required: true

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  token-upload:
    name: Upload Tokens
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Use Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Setup Cache & Install Dependencies
        uses: ./.github/actions/install-dependencies
      - name: Upload Tokens
        working-directory: packages/blade
        run: node ./scripts/uploadTokens.js '${{ github.event.inputs.tokens }}'  # nosemgrep: yaml.github-actions.security.run-shell-injection.run-shell-injection
        env: 
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

